export enum RegistrationStatus {
    SCHOOL_NOT_REPRESENTED = "SCHOOL_NOT_REPRESENTED",
    EVENT_FULL = "EVENT_FULL",
    PARTICIPATE = "PARTICIPATE",
    NOT_VALID = "NOT_VALID",
    VALID = "VALID",
    VALIDATE = "VALIDATE",
    PENDING = "PENDING"
}
